// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.2
// source: math1.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MathService_AddTwoNumbers_FullMethodName      = "/math.MathService/AddTwoNumbers"
	MathService_MultiplyTwoNumbers_FullMethodName = "/math.MathService/MultiplyTwoNumbers"
)

// MathServiceClient is the client API for MathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service 1: Math operations
type MathServiceClient interface {
	AddTwoNumbers(ctx context.Context, in *TwoNumbersRequest, opts ...grpc.CallOption) (*TwoNumbersResponse, error)
	MultiplyTwoNumbers(ctx context.Context, in *TwoNumbersRequest, opts ...grpc.CallOption) (*TwoNumbersResponse, error)
}

type mathServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMathServiceClient(cc grpc.ClientConnInterface) MathServiceClient {
	return &mathServiceClient{cc}
}

func (c *mathServiceClient) AddTwoNumbers(ctx context.Context, in *TwoNumbersRequest, opts ...grpc.CallOption) (*TwoNumbersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwoNumbersResponse)
	err := c.cc.Invoke(ctx, MathService_AddTwoNumbers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) MultiplyTwoNumbers(ctx context.Context, in *TwoNumbersRequest, opts ...grpc.CallOption) (*TwoNumbersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwoNumbersResponse)
	err := c.cc.Invoke(ctx, MathService_MultiplyTwoNumbers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathServiceServer is the server API for MathService service.
// All implementations must embed UnimplementedMathServiceServer
// for forward compatibility.
//
// Service 1: Math operations
type MathServiceServer interface {
	AddTwoNumbers(context.Context, *TwoNumbersRequest) (*TwoNumbersResponse, error)
	MultiplyTwoNumbers(context.Context, *TwoNumbersRequest) (*TwoNumbersResponse, error)
	mustEmbedUnimplementedMathServiceServer()
}

// UnimplementedMathServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMathServiceServer struct{}

func (UnimplementedMathServiceServer) AddTwoNumbers(context.Context, *TwoNumbersRequest) (*TwoNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTwoNumbers not implemented")
}
func (UnimplementedMathServiceServer) MultiplyTwoNumbers(context.Context, *TwoNumbersRequest) (*TwoNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiplyTwoNumbers not implemented")
}
func (UnimplementedMathServiceServer) mustEmbedUnimplementedMathServiceServer() {}
func (UnimplementedMathServiceServer) testEmbeddedByValue()                     {}

// UnsafeMathServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MathServiceServer will
// result in compilation errors.
type UnsafeMathServiceServer interface {
	mustEmbedUnimplementedMathServiceServer()
}

func RegisterMathServiceServer(s grpc.ServiceRegistrar, srv MathServiceServer) {
	// If the following call pancis, it indicates UnimplementedMathServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MathService_ServiceDesc, srv)
}

func _MathService_AddTwoNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).AddTwoNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathService_AddTwoNumbers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).AddTwoNumbers(ctx, req.(*TwoNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_MultiplyTwoNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).MultiplyTwoNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathService_MultiplyTwoNumbers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).MultiplyTwoNumbers(ctx, req.(*TwoNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MathService_ServiceDesc is the grpc.ServiceDesc for MathService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MathService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "math.MathService",
	HandlerType: (*MathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTwoNumbers",
			Handler:    _MathService_AddTwoNumbers_Handler,
		},
		{
			MethodName: "MultiplyTwoNumbers",
			Handler:    _MathService_MultiplyTwoNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "math1.proto",
}

const (
	ArrayService_SumArray_FullMethodName = "/math.ArrayService/SumArray"
	ArrayService_FindMax_FullMethodName  = "/math.ArrayService/FindMax"
)

// ArrayServiceClient is the client API for ArrayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service 2: Array operations
type ArrayServiceClient interface {
	SumArray(ctx context.Context, in *ArrayRequest, opts ...grpc.CallOption) (*ArrayResponse, error)
	FindMax(ctx context.Context, in *ArrayRequest, opts ...grpc.CallOption) (*ArrayResponse, error)
}

type arrayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArrayServiceClient(cc grpc.ClientConnInterface) ArrayServiceClient {
	return &arrayServiceClient{cc}
}

func (c *arrayServiceClient) SumArray(ctx context.Context, in *ArrayRequest, opts ...grpc.CallOption) (*ArrayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArrayResponse)
	err := c.cc.Invoke(ctx, ArrayService_SumArray_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arrayServiceClient) FindMax(ctx context.Context, in *ArrayRequest, opts ...grpc.CallOption) (*ArrayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArrayResponse)
	err := c.cc.Invoke(ctx, ArrayService_FindMax_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArrayServiceServer is the server API for ArrayService service.
// All implementations must embed UnimplementedArrayServiceServer
// for forward compatibility.
//
// Service 2: Array operations
type ArrayServiceServer interface {
	SumArray(context.Context, *ArrayRequest) (*ArrayResponse, error)
	FindMax(context.Context, *ArrayRequest) (*ArrayResponse, error)
	mustEmbedUnimplementedArrayServiceServer()
}

// UnimplementedArrayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArrayServiceServer struct{}

func (UnimplementedArrayServiceServer) SumArray(context.Context, *ArrayRequest) (*ArrayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SumArray not implemented")
}
func (UnimplementedArrayServiceServer) FindMax(context.Context, *ArrayRequest) (*ArrayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMax not implemented")
}
func (UnimplementedArrayServiceServer) mustEmbedUnimplementedArrayServiceServer() {}
func (UnimplementedArrayServiceServer) testEmbeddedByValue()                      {}

// UnsafeArrayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArrayServiceServer will
// result in compilation errors.
type UnsafeArrayServiceServer interface {
	mustEmbedUnimplementedArrayServiceServer()
}

func RegisterArrayServiceServer(s grpc.ServiceRegistrar, srv ArrayServiceServer) {
	// If the following call pancis, it indicates UnimplementedArrayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArrayService_ServiceDesc, srv)
}

func _ArrayService_SumArray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArrayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArrayServiceServer).SumArray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArrayService_SumArray_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArrayServiceServer).SumArray(ctx, req.(*ArrayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArrayService_FindMax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArrayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArrayServiceServer).FindMax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArrayService_FindMax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArrayServiceServer).FindMax(ctx, req.(*ArrayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArrayService_ServiceDesc is the grpc.ServiceDesc for ArrayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArrayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "math.ArrayService",
	HandlerType: (*ArrayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SumArray",
			Handler:    _ArrayService_SumArray_Handler,
		},
		{
			MethodName: "FindMax",
			Handler:    _ArrayService_FindMax_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "math1.proto",
}
