// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.2
// source: math1.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TwoNumbersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number1       float32                `protobuf:"fixed32,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2       float32                `protobuf:"fixed32,2,opt,name=number2,proto3" json:"number2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoNumbersRequest) Reset() {
	*x = TwoNumbersRequest{}
	mi := &file_math1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoNumbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoNumbersRequest) ProtoMessage() {}

func (x *TwoNumbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_math1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoNumbersRequest.ProtoReflect.Descriptor instead.
func (*TwoNumbersRequest) Descriptor() ([]byte, []int) {
	return file_math1_proto_rawDescGZIP(), []int{0}
}

func (x *TwoNumbersRequest) GetNumber1() float32 {
	if x != nil {
		return x.Number1
	}
	return 0
}

func (x *TwoNumbersRequest) GetNumber2() float32 {
	if x != nil {
		return x.Number2
	}
	return 0
}

type TwoNumbersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoNumbersResponse) Reset() {
	*x = TwoNumbersResponse{}
	mi := &file_math1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoNumbersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoNumbersResponse) ProtoMessage() {}

func (x *TwoNumbersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_math1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoNumbersResponse.ProtoReflect.Descriptor instead.
func (*TwoNumbersResponse) Descriptor() ([]byte, []int) {
	return file_math1_proto_rawDescGZIP(), []int{1}
}

func (x *TwoNumbersResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type ArrayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       []float32              `protobuf:"fixed32,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"` // An array of float numbers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayRequest) Reset() {
	*x = ArrayRequest{}
	mi := &file_math1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayRequest) ProtoMessage() {}

func (x *ArrayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_math1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayRequest.ProtoReflect.Descriptor instead.
func (*ArrayRequest) Descriptor() ([]byte, []int) {
	return file_math1_proto_rawDescGZIP(), []int{2}
}

func (x *ArrayRequest) GetNumbers() []float32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type ArrayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"` // Result for sum or max
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayResponse) Reset() {
	*x = ArrayResponse{}
	mi := &file_math1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayResponse) ProtoMessage() {}

func (x *ArrayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_math1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayResponse.ProtoReflect.Descriptor instead.
func (*ArrayResponse) Descriptor() ([]byte, []int) {
	return file_math1_proto_rawDescGZIP(), []int{3}
}

func (x *ArrayResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_math1_proto protoreflect.FileDescriptor

const file_math1_proto_rawDesc = "" +
	"\n" +
	"\vmath1.proto\x12\x04math\"G\n" +
	"\x11TwoNumbersRequest\x12\x18\n" +
	"\anumber1\x18\x01 \x01(\x02R\anumber1\x12\x18\n" +
	"\anumber2\x18\x02 \x01(\x02R\anumber2\",\n" +
	"\x12TwoNumbersResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result\"(\n" +
	"\fArrayRequest\x12\x18\n" +
	"\anumbers\x18\x01 \x03(\x02R\anumbers\"'\n" +
	"\rArrayResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result2\x9a\x01\n" +
	"\vMathService\x12B\n" +
	"\rAddTwoNumbers\x12\x17.math.TwoNumbersRequest\x1a\x18.math.TwoNumbersResponse\x12G\n" +
	"\x12MultiplyTwoNumbers\x12\x17.math.TwoNumbersRequest\x1a\x18.math.TwoNumbersResponse2w\n" +
	"\fArrayService\x123\n" +
	"\bSumArray\x12\x12.math.ArrayRequest\x1a\x13.math.ArrayResponse\x122\n" +
	"\aFindMax\x12\x12.math.ArrayRequest\x1a\x13.math.ArrayResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_math1_proto_rawDescOnce sync.Once
	file_math1_proto_rawDescData []byte
)

func file_math1_proto_rawDescGZIP() []byte {
	file_math1_proto_rawDescOnce.Do(func() {
		file_math1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_math1_proto_rawDesc), len(file_math1_proto_rawDesc)))
	})
	return file_math1_proto_rawDescData
}

var file_math1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_math1_proto_goTypes = []any{
	(*TwoNumbersRequest)(nil),  // 0: math.TwoNumbersRequest
	(*TwoNumbersResponse)(nil), // 1: math.TwoNumbersResponse
	(*ArrayRequest)(nil),       // 2: math.ArrayRequest
	(*ArrayResponse)(nil),      // 3: math.ArrayResponse
}
var file_math1_proto_depIdxs = []int32{
	0, // 0: math.MathService.AddTwoNumbers:input_type -> math.TwoNumbersRequest
	0, // 1: math.MathService.MultiplyTwoNumbers:input_type -> math.TwoNumbersRequest
	2, // 2: math.ArrayService.SumArray:input_type -> math.ArrayRequest
	2, // 3: math.ArrayService.FindMax:input_type -> math.ArrayRequest
	1, // 4: math.MathService.AddTwoNumbers:output_type -> math.TwoNumbersResponse
	1, // 5: math.MathService.MultiplyTwoNumbers:output_type -> math.TwoNumbersResponse
	3, // 6: math.ArrayService.SumArray:output_type -> math.ArrayResponse
	3, // 7: math.ArrayService.FindMax:output_type -> math.ArrayResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_math1_proto_init() }
func file_math1_proto_init() {
	if File_math1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_math1_proto_rawDesc), len(file_math1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_math1_proto_goTypes,
		DependencyIndexes: file_math1_proto_depIdxs,
		MessageInfos:      file_math1_proto_msgTypes,
	}.Build()
	File_math1_proto = out.File
	file_math1_proto_goTypes = nil
	file_math1_proto_depIdxs = nil
}
